### ISSUE TITLE
Investigate fixing GetCurrentCrosshairRef()

### ISSUE THREAD

**Issue by Odie** [Odie/skyui-vr#10]
When the VR wand is over an object, some UI code is activated and displays the information about the object. It might be possible to set update CurrentCrosshairRef via SKSE then. This will enable certain mods that depend on some valid object to be under the crosshair.

**Comment by grc472** [comment]
This would be a great improvement.  It seems that you would need to distinguish between the left hand and the right.  Only one of them can activate things, presumably it is whichever one you chose as primary.  You probably will need an SKSE plugin to provide a new function for setting the crosshair ref, because I don't thing SKSE provides that.  At least there is no Papyrus native function for it that I can see.

**Comment by Odie** [comment]
I actually did investigate this. 

The relevant UI code is not getting any kind of useful information regarding the item. It’s only sent some strings and numbers to be displayed.

:(

**Comment by grc472** [comment]
Damn.  I guess the only way it gets done is if the SKSE team steps up and does it internally.

**Comment by Odie** [comment]
Closing stale issue.
