### ISSUE TITLE
Getting an outdated SKSEVR error & are you still working on this project?

### ISSUE THREAD

**Issue by kamikazeedriver** [Odie/skyui-vr#34]
I have SKSEVR: "Current VR build 2.0.10 (runtime 1.4.15)"
That's the latest one on the script extender page, but it tells me my Script extender is outdated.

Also, I know you're busy, but are you still working on this project?

**Comment by Odie** [comment]
Howdy!

Can you attach a screenshot? It's been some time since I've fired up SVR and I don't think I saw ppl on the subreddit talking about game updates or skse breakages.

Yeah, it's a bit unfortunate, but I'm not currently working on improving skyui anymore. I was looking to overhaul the way skyui deals with input. Not sure if I have the will to see it through at the moment. :(

**Comment by rbturcott** [comment]
I have the same setup but am not experiencing any version errors.  (or any skyui-vr errors at all)
I'm not at my game to check, but it may be because in skyui setup (for itself under advanced or something) you can disable version alerts, but I don't recall doing that for skyui-vr.
(Thank you very much for your work, by the way :-) )

**Comment by Odie** [comment]
@rbturcott You’re very welcome! Glad things are working for you. =)

IIRC, version checking should be off by default now. So, they really shouldn’t be coming up.

**Comment by kamikazeedriver** [comment]
Ok, my apologies, I put in this, as well as racemenu at the same time, and I assumed the error was coming from your SkyUI VR beta, and not racemenu.  
This is working great for me.  

I hadn't played in a few months, and apparently I had loaded SkyUI at some point, realized it didn't work and had removed it but took a hiatus from the game.
Decided to start it back up the other day, and when I loaded my savegame, it said SkyUI was missing, and I just thought, yeah because it doesn't work in VR.  No big deal I thought, but then I realized i couldn't save without crashing, or even when the game would attempt to autosave, it would crash.  
After some troubleshooting, I finally loaded SkyUI back in and aside from the UI errors, the game worked normal, I could save etc.  But of course, since SkyUI doesn't get along with the VR version of Skyrim, that's not really an option.  I guess I have somehow messed up my savegame to NEED SkyUI installed, I don't know.  
Anyway, then I found your mod. 
This allows me to continue my savegame.  I thank you very much for making this.  

Sorry to hear you're no longer working on it.  Perhaps you could release it's current beta on Nexusmods.
If you mentioned you no longer have time to work on it, but are releasing it as is, perhaps someone will see it and be willing to pick up where you left off.  It's worth a shot.  This has great potential.

**Comment by Odie** [comment]
I’ve contacted admins over at the nexus about releasing the mod. They wanted to get permission from the original SkyUI author and helped in reaching out to him. But apparently, he never did reply to their message. This means I don’t have permission, and cannot release the altered mod there.

Anyway... glad things are working for you now. Have fun with the game! =)

**Comment by trenon1** [comment]
Hello, I am getting this error as well, SKSEVR and SKYUIVR both are current yet I get the outdated SKSE error. Any idea?

**Comment by Odie** [comment]
@trenon1 It doesn’t look like there is a new version of sksevr. Please check if you’re actually launching the game via skse.
