### ISSUE TITLE
Can't access my inventory in barter screen

### ISSUE THREAD

**Issue by tdavenport34** [Odie/skyui-vr#38]
In the controls section it states that "In the barter menu or the gift menu, keep hitting "left" until you've reached the first item on the category list (titled "All"). Hit "left" again and the trade direction should toggle.", but for me it just keeps cycling through the merchant's categories.

**Comment by Odie** [comment]
Hi there!

What’s your setup like? I’ve only tested this on a vive. Though I don’t remember people reporting this particular feature being broken other than in the first few alpha versions.

**Comment by quietlychamil** [comment]
This is also happening to me.  Swiping or clicking left does not seem to allow me to access my inventory screen to barter, it just cycles through the merchant's inventory.

**Comment by quietlychamil** [comment]
I have two mods affecting the SKYUI interface, which are "Colored And Animated Celtic Icons For SkyUI SE" and "SkyUI Themes - The Adventurer WIP SE"  I haven't tested to see if one of these are an issue because the mod, "VR Menu Mouse Fix" works really well as a fix.  I can just point and click to change tabs.

Anyways, thank you for all your excellent work, Odie!  This really is a game changer for VR!
