### ISSUE TITLE
Incompatible with Hide SkyUI

### ISSUE THREAD

**Issue by sw201444** [Odie/skyui-vr#40]
https://www.nexusmods.com/skyrimspecialedition/mods/12770

When adding hideskyui the controls break and can no longer be seen 

I don't like skyui's menus but mods depend on it, and I appreciate you porting it nonetheless!

**Comment by Odie** [comment]
Hi there,

It looks like Hide SkyUI simply reintroduces the game’s original files back into your load order. But, it reintroduces the menu files from SE instead of from the VR version.

So, it’s not really that SkyUI VR doesn’t work with Hide SkyUI. It’s that Hide SkyUI is not compatible with Skyrim VR itself.

If you want to get the vanilla menus back, it’s simple enough to unzip SkyUI VR and delete swf files that you don’t want. The mod menu should continue to work as long as you keep the quest_jiurnal.swf around.

Hope that help!

**Comment by sw201444** [comment]
> Hi there,
> 
> It looks like Hide SkyUI simply reintroduces the game’s original files back into your load order. But, it reintroduces the menu files from SE instead of from the VR version.
> 
> So, it’s not really that SkyUI VR doesn’t work with Hide SkyUI. It’s that Hide SkyUI is not compatible with Skyrim VR itself.
> 
> If you want to get the vanilla menus back, it’s simple enough to unzip SkyUI VR and delete swf files that you don’t want. The mod menu should continue to work as long as you keep the quest_jiurnal.swf around.
> 
> Hope that helps!

Ah awesome! Thanks for getting back so quick!

**Comment by sw201444** [comment]
As an update, as you stated delete the ones that arent needed 

but fopr mod organizer you do need the QuestJournal SWF one, and after that they are all gone except what's needed

Figured I'd update in case anyone else is looking for the solution
