### ISSUE TITLE
Keep Getting SkyUI Error Code 1

### ISSUE THREAD

**Issue by EpicFaces1337** [Odie/skyui-vr#43]
So I just got SkyrimVR and noticed that as soon as I install SKYUI with VRIK Player Avatar, I get Error Code 1. I have the latest SKSEVR and SKYUI VR, automatically sorted the plugins with LOOT, and I still get the error. Every other mod I have installed that doesn't need SKYUI seems to work just fine. Am I missing something here?

**Comment by Odie** [comment]
I think that error says skse isn’t running. You can check if skse is running using the “getskseversion” console command.

To fix this problem, make sure to launch the game via the skse loader, assuming you’ve installed skse correctly. If you’re not sure, check this guide: https://www.reddit.com/r/skyrimvr/comments/a645lm/guide_how_to_install_skse_vr_and_skyui_vr/

The guys over on the r/skyrimvr have lots of getting started guides. They’re usually really helpful as well.

**Comment by EpicFaces1337** [comment]
> 
> 
> I think that error says skse isn’t running. You can check if skse is running using the “getskseversion” console command.
> 
> To fix this problem, make sure to launch the game via the skse loader, assuming you’ve installed skse correctly. If you’re not sure, check this guide: https://www.reddit.com/r/skyrimvr/comments/a645lm/guide_how_to_install_skse_vr_and_skyui_vr/
> 
> The guys over on the r/skyrimvr have lots of getting started guides. They’re usually really helpful as well.

So I went through the SKSE guide you attached to make sure I have it installed correctly, launched it through SKSE, but it still doesn't work. Typed in "getskseversion" and says command not found. Not sure what to do from here.

**Comment by Odie** [comment]
Are you using MO? I took a closer look at the guide. It really doesn’t mention how to setup the shortcut to launch the game with skse for MO. You need to launch the game via MO to get the virtualized directories for the game to find the mod files. You also need configure MO so that it also launches the game via skse64_loader.exe for skse to inject itself into the game.

It’s been awhile since I’ve played Skyrim. I don’t remember the details enough to give you a step by step. Try searching for something like “how to launch skse with MO”. Otherwise, I’d suggest posting a question on r/skyrimvr. :(

**Comment by EpicFaces1337** [comment]
I use Vortex to install my mods and I’m creating the shortcut for SKSE VR but it does not seem to be working. I will go see if r/skyrimvr will help me. I appreciate you trying to help me.

**Comment by Odie** [comment]
No problem. Best of luck. Hope you get to start enjoying the game soon!
