### ISSUE TITLE
SkyUI breaks HTC Vive Trackpad Movement

### ISSUE THREAD

**Issue by Chaozs** [Odie/skyui-vr#44]
# Hardware:
HTC Vive
AMD Ryzen 5 3600
GTX 1070

# Software:
Windows 10 Education, Version 1909
SteamVR 1.13.10
Vortex 1.2.20
SKSE VR build 2.0.12
SkyUI VR release v1.0-beta.4

# Bug (?) issue:
On a fresh install of Skyrim VR on Steam, I have installed SKSE VR, and SkyUI VR through vortex. With only those 2 mods enabled, I am able to successfully deploy, launch, AND check SkyUI settings through the ingame mod-manager. I am however unable to utilize the HTC Vive trackpad for direct movement, or teleport movement. (SkyUI controls for UI all work) I am assuming the trackpad is always being taken by SkyUI for the UI control, and is never letting it access in-game character movement? The movement works fine during first-time VR setup, when SkyUI is not active. I have also tried restarting a new game multiple times to doublecheck, and I can also confirm that if I disable SkyUI and run vanilla + SKSE, I have no issues with trackpad movement.

Any assistance would be greatly appreciated!

If there is any other information you would like me to provide, please let me know!

**Comment by Odie** [comment]
That's really strange. I was running it on a vive pro. I don't think I've ever had a non-responsive trackpad issue, even before I tried patching SkyUI(SE).

It's been quite some time since I did any work on SkyUI. My recollection of details is a bit fuzzy. AFAIK, the swf files that are included in the skyui release never tries to take over or read the trackpad directly. It is quite passive in that it is only able to process and receive UI events sent by the game engine.

Are you sure the only mods active is SKSE and SkyUI? If you suspect something is redirecting all the input signals, you might want to check if you have Skyrim VR Tools or other mods that require it activated. Skyrim VR Tools is quite able to block the game from receiving input signals.

**Comment by Chaozs** [comment]
Hmm since SkyUI  never tries to take over the trackpad, I'll assume it's something else. I do have Skyrim VR Tools with Weapon Throw VR, but both are disabled on vortex- I guess SkyUI may somehow trigger those to become active. I'll assume it's something else then and close this issue. Thank you for your help!
