### ISSUE TITLE
If Campfire and Frostfall Unofficial Update overwrites this mod then Can't Loot items from containers/corpses?!

### ISSUE THREAD

**Issue by ntblood** [Odie/skyui-vr#48]
I noticed that if you have this mod overwritten by "Campfire and Frostfall - Unofficial SSE Update" 
(download file name: "Campfire 1.12.1 and Frostfall 3.4.1SE") from
https://www.nexusmods.com/skyrimspecialedition/mods/17925  

..then you can't loot items off corpses or take items from containers.
I don't have Frostfall installed, just Campfire.  Is this a common issue? Any ideas?
Thanks

**Comment by Odie** [comment]
You’ll want to try this:
https://github.com/angrmgmt/skyui-vr/releases/tag/v1.0F-beta.1

You can find the Reddit post here:
https://www.reddit.com/r/skyrimvr/comments/aer3rt/frostfall_compatibility_patch_for_skyuivr/

**Comment by ntblood** [comment]
Ok, thank you. I don't have Frostfall installed, just Campfire. 
I was just told this, "Campfire and Frostfall - Unofficial SSE Update": "this mod is not needed when you use (last) campfire version alone (no Frostfall)."

**Comment by Odie** [comment]
Sorry, I'm having trouble understanding which version you installed.

There are a few different choices, it looks like:
1. Campfire 1.12.1SEVR Release[from here](https://www.nexusmods.com/skyrimspecialedition/mods/667?tab=files)
2. Campfire 1.12.1 and Frostfall 3.4.1SE [from here](https://www.nexusmods.com/skyrimspecialedition/mods/17925?tab=files)
3. Campfire 1.11SE only [from here](https://www.nexusmods.com/skyrimspecialedition/mods/17925?tab=files)

If you just want to run Campfire, you probably want to choose the 1, the VR specific option. If you're running 2, it comes packaged with a custom version of skyui for SSE, which would not work correctly with Skyrim VR. In this case, you want to use [this version of skyui-vr instead](https://github.com/angrmgmt/skyui-vr/releases/tag/v1.0F-beta.1). If you're running 3, I'd suggest replacing it with 1, since it's the VR specific version.

---

Skyui (SSE) does not work with Skyrim VR. SSE and the VR versions of the game expect the menu system to work slightly differently for whatever reason. When run with Skyrim VR, Skyui (SSE) usually became unresponsive shortly after calling up the menu for the first time. This is why if you installed choice #2 from above, It simply wouldn't work.

Hope that helps!

**Comment by ntblood** [comment]
That version list has me a bit confused. I am using 1. Campfire 1.12.1SEVR Release.  
The other ones, 2 & 3, are both, from what I can tell, a patch/"update" which requires Campfire/Frostfall or both but that does not play well with Campfire VR as you seemed to mention. It prevents placement of the Campfire and also it it overwrites SkyUI VR it'll prevent taking objects from containers or corpses I've found.

**Comment by ntblood** [comment]
Dang it. When I removed the C-F Unoff. Update (patch) earlier I was able to place a campfire. Now for some reason I can't again. Only thing in MO2 that is overwriting Sky UI VR now is DearDiary VR version (custom made by TheRetroCarrot, soon to be released) but that was fine before.

**Comment by ntblood** [comment]
Dang it. When I removed the C-F Unoff. Update (patch) earlier I was able to place a campfire. Now for some reason I can't again. Only thing in MO2 that is overwriting Sky UI VR now is DearDiary VR version (custom made by TheRetroCarrot, soon to be released) but that was fine before.

**Comment by ntblood** [comment]
Yeah, moving the SkyUI VR plugin back down in my plugin LO in MO2 fixed the issue again. I can place campfires again. Thank goodness!  ^_^*   Thank you

**Comment by ntblood** [comment]
To solve not being able to take items from containers/corpses Or not being able to place campfires: The issue is when any of SkyUI VR's files are overwritten in the left panel of MO2 by anything other than DearDiary VR (that one should actually overwrite SkyUI VR). Then the other possible cause is if the SkyUI VR plugin (right-panel of MO2) is too high in the load order. Try moving the SkyUI VR plugin (SkyUI_SE.esp) lower in your right-panel MO2 load order. Don't have it toward the top. Also if anything is overwriting SkyUI VR's files in the left panel of MO2 (that would be a problem) (other than DearDiary VR pre-release so not yet).
