### ISSUE TITLE
Delay when opening any container/body

### ISSUE THREAD

**Issue by jekyllgrim** [Odie/skyui-vr#53]
This is essentially a duplicate of #39, except the solution mentioned there doesn't work for me, and if the issue is about "the pex files that comes with SKSE were not installed/activated correctly", I have no idea how to fix that. I've installed v1.0-beta.4 by unpacking it into my SkyrimVR folder. It seems to work otherwise, except the lag. Any tips?

**Comment by Odie** [comment]
Hi there!

It has been a long time since I fired up SkyrimVR. IIRC, the pen files can be installed via MO2 or just copied over to the SkyrimVR install directory directly.

You’ll be able to find more detailed instruction here.

https://www.reddit.com/r/skyrimvr/comments/a645lm/guide_how_to_install_skse_vr_and_skyui_vr
