### ISSUE TITLE
Will not recognize sksevr

### ISSUE THREAD

**Issue by Jkale91** [Odie/skyui-vr#56]
I have tried the latest and previous iteration of sksevr with skyui vr and for the life of me I can't get skyui to acknowledge sksevr is running. Idk if theres a version error or if I legitimately am missing something in the steps, but I have uninstalled both and reinstalled them many times.

**Comment by Odie** [comment]
Hi there,

Which mod manager are you using? What steps did you take to install skse and skyui? If you have skse installed correctly, installing skyui should just be drag-and-drop + click checkbox to enable the mod. If you're having trouble, I'd guess it's because skse wasn't installed correctly.

Here's a short checklist to see if skse is running correctly.
1. Did you copy sksevr binary files files into your game installation directory?
2. Did you enable pex files in sksevr's data folder?
3. Did you launch the game using skse_loader?
4. When you run the `getskseversion` command in the console, do you get a valid response?

Hope this helps resolve your problem!

**Comment by Jkale91** [comment]
LMAO I have no idea what I did differently this time but I got it working XD, thank you for your time and promptness!
