### ISSUE TITLE
Slow Loading

### ISSUE THREAD

**Issue by red48car** [Odie/skyui-vr#79]
I was wondering if you could fix the loading time or maybe just speed it up, so the menu shows instantly after opening it. 
I don't know if this is just a normal timed thing for inventory opening on Skyrim but it seems rather slow. Sometimes it even lags your game a ton and then the background goes black. Not sure if this classifies as an issue but this is my only inventory managing mod I have installed so I don't see why else this would affect the loading speeds of the menu. 

Just looking for a simple fix or a bit of guidance.

**Comment by Odie** [comment]
You might want to check if the skse script files are actually installed. When it’s not installed, it takes an unreasonable of time for the menu to start responding.

The other thing that might be happening is there are too many items in the inventory. One way to work around the issue is to drop off all your items periodically.

**Comment by red48car** [comment]
Turns out you're completely right. I installed it manually but I must of not done it right or something.

I **HIGHLY RECOMMEND** everyone that installs this mod to do it through NMM and just drop the 7z file. It completely solved this issue.

Also thanks for responding very quickly. You and whoever made SKYUI are now some of my favorite modders of all time. I just installed the Paperbook menu port for VR and now I can officially be completely satisfied with my mods.
